# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  bs-platform = nodeEnv.buildNodePackage {
    name = "bs-platform";
    packageName = "bs-platform";
    version = "5.0.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/bs-platform/-/bs-platform-5.0.6.tgz";
      sha512 = "6Boa2VEcWJp2WJr38L7bp3J929nYha7gDarjxb070jWzgfPJ/WbzjipmSfnu2eqqk1MfjEIpBipbPz6n1NISwA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "bucklescript compiler, ocaml standard libary by bucklescript and its required runtime support";
      homepage = "https://github.com/bucklescript/bucklescript#readme";
      license = "SEE LICENSE IN LICENSE";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}